config/routes.rb
Rails.application.routes.draw do
  get '/search' => 'search#search'
  devise_for :users
  root 'home#top'
  get 'home/about'
  resources :users do
    member do
     get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @books = Book.all
    @user = User.find(@book.user_id)
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def new
     @book = current_user.posts.build
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<% if @book.errors.any? %>
	<div class="alert alert-warning">
		<%= @book.errors.count %>errors prohibited this book from being saved:<br>
			<ul>
			<% @book.errors.full_messages.each do |message| %>
  				<li><%= message %></li>
			<% end %>
			</ul>
	</div>
<% end %>
<div class="row">
	<%= form_for(book) do |f| %>
		<div class="field row">
			<%= f.label :title %>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
		</div>

		<div class="field row">
			<%= f.label :body %>
			<%= f.text_area :body, class: "col-xs-12 book_body" %>
		</div>

		<div class="actions row">
			<%= f.submit class: "btn btn-primary col-xs-12" %>
		</div>
	<% end %>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
	<div class="alert alert-warning">
		<%= @book.errors.count %>errors prohibited this book from being saved:<br>
			<ul>
			<% @book.errors.full_messages.each do |message| %>
  				<li><%= message %></li>
			<% end %>
			</ul>
	</div>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">

			<h1>Editing Book</h1>

			<%= form_for(@book) do |f| %>
				<div class="row">
				  	<h4>Title</h4>
				  	<%= f.text_field :title, class:"col-xs-12" %>
			  	</div>
			  	<div class="row">
		  			<h4>Opinion</h4>
		  			<%= f.text_area :body, class:"col-xs-12" %>
				</div>
				<div class="actions row">
			  		<%= f.submit 'Update Book', class:"btn btn-primary col-xs-12" %>
			  	</div>
			  	<%= link_to "Show", book_path(@book.id) %>
			  	<a >|</a>
			  	<%= link_to "Back", books_path %>
			<% end %>

		</div>
		<div class="col-md-3"></div>

	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book.id), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>
							<% if book.favorited_by?(current_user) %>
								  <%= link_to book_favorites_path(book.id), method: :delete do %>
								    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
								    <%= book.favorites.count %>
								  <% end %>
								<% else %>
								  <%= link_to book_favorites_path(book.id), method: :post do %>
								    <i class="fa fa-heart-o" aria-hidden="true"></i>
								    <%= book.favorites.count %>
								  <% end %>
							<% end %>
						</td>
						<td><%= book.book_comments.count %>件コメント</td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<!--books一覧 -->


		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @book_new %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<td>
						<% if @book.favorited_by?(current_user) %>
							  <%= link_to book_favorites_path(@book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    <%= @book.favorites.count %>
							  <% end %>
							<% else %>
							  <%= link_to book_favorites_path(@book), method: :post do %>
							    <i class="fa fa-heart-o" aria-hidden="true"></i>
							    <%= @book.favorites.count %>
							  <% end %>
						<% end %>
					</td>
					<td><%= @book.book_comments.count %>件コメント</td>
					<% if @book.user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@book.id), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<ol>
			  <% @book.book_comments.each do |book_comment| %>

			      <div class="comment-body bb">
			        <div class="comment-text">
			          <div class="comment-author clearfix">
			          	<%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %>
			            <%= book_comment.comment %>
			            <% if book_comment.user == current_user %>
					    	<%= link_to "Destroy", book_book_comment_path(book_comment.book_id, book_comment), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
					    <% end %>
			          </div>
			          <a href="#" class="link-author"><%= book_comment.user.name %></a>
			        </div>
			      </div>
			  <% end %>
			</ol>
			<%= form_for [@book, @book_comment] do |f| %>
			  <div class="row">
			    <div class="col-sm-12">
			      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			    </div>
			  </div>
			  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>

		</div>
	</div>

</div>